config/routes.rb
Rails.application.routes.draw do
  resources :seasons

  devise_for :users
  resources :shows
  resources :videos

  root 'shows#index'

end

app/models/season.rb
class Season < ActiveRecord::Base
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :videos

  def watched
    videos.select { |video| video.is_watched }
  end

  def unwatched
    videos.select { |video| !video.is_watched }
  end

  def percent_watched
    watched.count.to_f / videos.count
  end

  def fraction_out_of_ten_watched
    (percent_watched * 10).floor
  end

  def percent_bar
    string = "|#{'-' * fraction_out_of_ten_watched}#{" " * (10 - fraction_out_of_ten_watched)}|"
    string.gsub(' ', '&nbsp;').html_safe
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :show
  mount_uploader :file, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:number, :show_id)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to show_path(@video.show), notice: 'Video was successfully created.' }
        format.json { render :index, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to show_path(@video.show), notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :show_id, :user_id, :is_movie, :is_watched, :bookmark, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyWatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.number_field :show_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h1>Listing seasons</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.number %></td>
        <td><%= season.show_id %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @season.number %>
</p>

<p>
  <strong>Show:</strong>
  <%= @season.show_id %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_table.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th class="watched-header"><span class="glyphicon glyphicon-eye-open"></span></th>
      <th>Episode</th>
      <th>Progress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @show.videos.each do |video| %>
      <tr>
        <td>
          <%= link_to((video.is_watched ? check_box_tag(nil, nil, checked: true) : check_box_tag(nil)),
              video_path(video, video: {is_watched: !video.is_watched }), method: :patch) %></td>
        <td><%= link_to video.name, video %></td>
        <td><%= video.bookmark %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Listing shows</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Progress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= link_to show.name, show %></td>
        <td><span class="percent"><%= show.percent_bar %></span></td>
        <td><%= link_to 'Show', show %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @show.name %></h1>

<%= render 'table' %>
<br>
<%= link_to 'Add Episode', new_video_path %>
<br>
<br>
<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <div class="form-group">
    <%= f.label :show_id %><br>
    <%= f.collection_select :show_id, Show.order(:name), :id, :name %><br>
  </div>
  <%= hidden_field_tag :user_id, current_user %>
  <div class="form-group watched-field">
    <%= f.label :is_watched, :hidden => 'true' %>
    <%= f.check_box :is_watched %> Watched? <br>
  </div>
  <div class="form-group">
    <%= f.label :file %><br>
    <%= f.file_field :file %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Show</th>
      <th>User</th>
      <th>Is movie</th>
      <th>Is watched</th>
      <th>Bookmark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <td><%= video.show_id %></td>
        <td><%= video.user_id %></td>
        <td><%= video.is_movie %></td>
        <td><%= video.is_watched %></td>
        <td><%= video.bookmark %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<% render 'table' %>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>
<br>
<p><%= link_to 'Back', videos_path %></p>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @video.name %></h1>
<% unless @video.is_movie %>
  <p><%= @video.show.name %></p>
<% end %>

<% if @video.is_watched %>
  <p><strong><em>Watched</em></strong></p>
<% end %>

<p>
  <strong>Bookmark:</strong>
  <%= @video.bookmark || "None" %>
</p>

<%= video_tag @video.file, :size => "320x240", :controls => true %>

<br>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', show_path(@video.show) %>